### ISSUE TITLE
Every languages are english

### ISSUE THREAD

**Issue by CaskMask** [Raytwo/ARCropolis#126]
it's been a while this is in most patches but it seem it isn't fixed still...?
When i use any languages, they all use the english voices exept on leaf i guess
Just hopping this get fixed soon

**Comment by Raytwo** [comment]
Sorry but your report really explains nothing and does not even provide an example to reproduce the issue.
Also please use one of the available templates to report issues.

**Comment by CaskMask** [comment]
How can i even reproduce an issue that makes everything english when i
don't even know what makes it do that ?
Also i issues are to report a problem so using the existing ones doesn't
makes sense

**Comment by jam1garner** [comment]
@CaskMask by 'template' he doesn't mean an existing issue, there is a provided template format that you fill out when filing an issue that asks you for things like what is expected to happen, what does your configuration file look like, what arcrop/switch/atmosphere version you're on, etc.

If you submit another issue using the template and providing your configuration file as well as your switch's system language and maybe what language you have set in smash ultimate's settings we then would be able to further help you due to having more info to work off of.

It's hard to understand the issue without having that necessary information. Hope you understand.
