### ISSUE TITLE
[Feature suggestion] Different toggled mods depending on the current user.

### ISSUE THREAD

**Issue by blu-dev** [Raytwo/ARCropolis#134]
## Feature suggestion
Allow different switch users to change which mods get loaded.

### What would the feature do?
When a user launches Smash, ARCropolis will fetch the user ID and change which mods it will load depending on that.

### How should it be implemented?
* Change the current system for determining which mods are enabled/disabled. Folder names starting with `.` should no longer be considered disabled, and instead this should be stored in a file on a per-user basis. The file should be updated every time ARCropolis discovers a new mod, and it will be enabled by default.

### Is there an alternative way of doing things you'd like to suggest?
N/A

### Additional information
N/A

**Comment by Raytwo** [comment]
As discussed in DMs, [skyline-config](https://github.com/skyline-rs/skyline-config) (Name subject to change) could be used to store the list of selected active mods on a per-user basis, with the added bonus of not exposing the file to the user, reducing the possibility of mishandling the file.

On first setup or if the file is missing, the user could be prompted to open the mod manager menu (ARCadia-rs) so that they can select the mods they want to use.
