### ISSUE TITLE
[Feature suggestion] File addition

### ISSUE THREAD

**Issue by blu-dev** [Raytwo/ARCropolis#142]
## Feature suggestion
File addition

### What would the feature do?
Any file discovered which is not already in the game's FS tables should be added at runtime.

### How should it be implemented?
ARCropolis should automatically add missing folders/files to the search section, and add missing files to the FilePath table. It then needs to resort all of the bsearch sections of the tables.

For adding files to DirInfos for the game to load them, that should be done via a `json` file in the root of the mod, probably associated with the explicit file table modifications.

### Is there an alternative way of doing things you'd like to suggest?
N/A

### Additional information
N/A

**Comment by ClaudevonRiegan** [comment]
One thing I would like to add is when you add files to say, Link c00, it will add files to that specific slot and not on others like c01, c02, etc. By default it should add on all slots and let them be shared unless specified otherwise by the user. So basically if you add a file on any one slot, it should add and share them on every slot unless user says not to do so.

**Comment by ElaineLMN** [comment]
Just curious, would this feature theoretically allow for skin slots past c07?

**Comment by Raytwo** [comment]
> Just curious, would this feature theoretically allow for skin slots past c07?

No, that'd be directory addition.

Closing this issue since file addition has been implemented now.
