### ISSUE TITLE
[Qualify of Life] If file patching fails, let the user know what file(s) failed

### ISSUE THREAD

**Issue by RocketRaccoon27** [Raytwo/ARCropolis#248]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### Explain what could get improvements.

The file patching process if something goes wrong. Right now if something goes wrong, the game will crash and it will be left up to the user to find what file(s) are messed up and sort them out. This can be problematic for people transitioning to file patching now and in the future if someone is creating something like a one slot Inkling mod. 

### How could we make this better?

Much like conflicts.json, give the user a file that tells them what the problematic file is. Specific errors like "Missing an </entry> at line XX" or what have you would be good but not necessary.

**Comment by Raytwo** [comment]
We sadly literally cannot do that, all we do is change the size in data.arc and provide your file to the game, we have no way of knowing what file crashed or what was the reason.

Even logging the last loaded file is useless because the game might load your file a few seconds before trying to use it and by then, other files would've been loaded.
