### ISSUE TITLE
Game crash on Startup (not the same as the other issue)

### ISSUE THREAD

**Issue by FreedomFeathers** [Raytwo/ARCropolis#27]
There was another issue relating to a game crash on startup, but this one gives a different message. 
![maxresdefault](https://user-images.githubusercontent.com/73450183/97124051-94443600-16fc-11eb-89f2-e5eeba56b739.jpg)

**Comment by AlexFenlon** [comment]
Same problem. Updated to latest 0.9.3 and the latest update for smash 9.0.1 and I cannot use arcopolis since I've updated.

**Comment by FreedomFeathers** [comment]
Someone told me updating latest switch update and game update fixed it, but they had to manually reinstall arcolopolis

**Comment by AlexFenlon** [comment]
Did not work, unfortunately. Just updated my switch firmware and nada, Everything is up to date and nothing. It's unfortunate but I guess I'll have to wait for a new release of arcopolis to hopefully fix it.

**Comment by Kekulism** [comment]
Same issue here. Crashing without even having installed any mods. This needs to be fixed, it's real frustrating.

**Comment by AlexFenlon** [comment]
> Same issue here. Crashing without even having installed any mods. This needs to be fixed, it's real frustrating.

Oh so frustrating. Yeah, I'm the same, tried with no mods as well. I alsoo hope it's fixed soon.

**Comment by Raytwo** [comment]
Hey there, sorry I've been taking a break lately.
I'm aware of a bug related to the config that affects a few people, however I do not know how to fix it yet.
ARCropolis is undergoing a rewrite for the time being so I can't prioritize fixing this, but it should be fixed with version 0.10.0 which should indirectly fix this (so far it seems to).
Please join the modding Discord if you need more explanations on a potential workaround.
