### ISSUE TITLE
Question: What programming language is used to develop mods for arc.

### ISSUE THREAD

**Issue by zzpixel** [Raytwo/ARCropolis#29]
What programming language is used to develop a mod for arc and what applications do I need? I know I need the data.arc file but I don't know what programming language it runs on. I'm guessing its rust based on my research but I am unfamiliar with it and what I need for it. Thank you.

**Comment by Raytwo** [comment]
Hello,
Seems like you got a bit confused along the way but hopefully this will answer your questions:

- Data.arc is an archive, a container. It holds the files for the game. If your goal is to make code mods (since you talk about programming languages), you technically do not need this.
- ARCropolis and most plugins for Smash are indeed made using the Rust programming language and Skyline-rs, however, C++ is also an alternative. Rust is probably the best option if you have no experience though.

For getting started, you can read here: [Skyline-rs](https://github.com/ultimate-research/skyline-rs-template/wiki)
