### ISSUE TITLE
Toggle on and off mods not working

### ISSUE THREAD

**Issue by foolishhabits** [Raytwo/ARCropolis#47]
I don't know if it's a weird file or if it's not working but it won't toggle this modded map of mine off.

**Comment by foolishhabits** [comment]
I can't play battlefield without a weird background now because I deleted the old mod file off my folder without toggling off.. is there a fix for this?

**Comment by foolishhabits** [comment]
hello?

**Comment by Genwald** [comment]
You can disable a mod by removing it from the folder that ARCropolis is set to load mods from, or by adding a "." to the front of the mod name folder if using the UMM style path. Beyond that, there is no "toggle" feature in ARCropolis as far as I know.  
This doesn't really sound like an issue with ARCropolis, because it can not load mods from folders other than the ones specified in the config and a mod can not persist after a reboot of the game without being loaded by ARCropolis again.  
For support, rather than issues with the program, join the ["Smash Ultimate Modding" Discord server](https://discord.gg/ASJyTrZ)

**Comment by foolishhabits** [comment]
https://user-images.githubusercontent.com/78168484/109252769-50e9f900-77bc-11eb-9b95-b76a7372958d.MOV

Don't mind the TV in the background. The video shows exactly the error. By the way, there was literally an error called "failed toggling", so there is a "toggle" feature. I'm trying the "." on the files but there seems to be an error with my Battlefield every time I load it.

**Comment by Genwald** [comment]
You are showing an error given by [Arcadia](https://github.com/Coolsonickirby/ARCadia). This issue is posted on the repo for ARCropolis.

**Comment by foolishhabits** [comment]
Oh my I'm sorry about that. Thanks for the insight!

**Comment by Raytwo** [comment]
Thanks Genwald, I'm closing this.
