### ISSUE TITLE
Having too many CSS .bntx causes crashes.

### ISSUE THREAD

**Issue by swampatha** [Raytwo/ARCropolis#8]
When having a lot of .bntx for CSS stuff (basically all of the chara_) stuff, the game crashes when loading any of the types of .bntx you're loading, even if the ones being loaded aren't modified. I don't know the exact number, but I've seen the number 25 thrown around on the Ultimate Modding Discord. I had it crash with probably about 75 total, but all were under the original filesize limit.

**Comment by ThatNintendoNerd** [comment]
I have just tested having 85 custom CSS icons of the exact same file size in bytes with ARCropolis and all successfully loaded. One file for you may have been over the file size limit due to having a bloated `_RLT` section in the BNTX. I'd suggest trying again, and if it works this issue can be closed.

**Comment by Raytwo** [comment]
This issue has been solved, the problem was files over the original size.
