### ISSUE TITLE
[Crash] [Multiple versions] Crash on boot

### ISSUE THREAD

**Issue by fartzgaming** [Raytwo/ARCropolis#83]
### Your setup
System firmware version: ``12.0.3``
Atmosphère version: ``0.19.4``
Smash version: ``12.0.0``
ARCropolis version: ``Tried 2.0.0-beta, 1.1.3, and 1.0.5``
microSD card format: ``FAT32``

### Reproducibility 
Every time I attempt to boot Ultimate, the game crashes. It says "Unable to start software. Return to HOME Menu and try again." Doesn't matter if I have mods or not. However it does boot when I hold L (aka Vanilla Ultimate).

### What happened and what's the context?
Literally just when I try to boot it.

### Configuration
I don't have an acropolis.toml file as I just installed it and transferred everything from UMM just as the guide told me to.

### Crash report
It doesn't crash my switch, just the game.

**Comment by GarnetSunset** [comment]
Same here, `
R:\Downloads>skyline_logger.py
Enter Switch's IP Address: 192.168.1.189
Enter Port Number (Leave Blank for Default (6969)):
Couldn't connect to socket! Trying again in 5 seconds.
[WinError 10061] No connection could be made because the target machine actively refused it
Socket Connection Success!
[skyline_main] Begining initialization.

[And64InlineHook] inline hook 0x7f528ee960->0x7f526b1578 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x7f52a422c0->0x7f526b69cc successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x7f52a42300->0x7f526b69cc successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x7f52a1e000->0x7f526b1570 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x7f528593d0->0x7f526b161c successfully! 4 bytes overwritten
[skyline_main] Mounted Rom (0x0)
[skyline_main] text: 0x7f4ac04000 | rodata: 0x7f4e56e000 | data: 0x7f4fa7d000 | bss: 0x7f51f9c000 | heap: 0x39a6600000
[SafeTaskQueue] Starting thread.
[SafeTaskQueue] Thread started.
[skyline_main] Mounted SD (0x0)
[PluginManager] Initializing plugins...
[PluginManager] Opening plugins...
[PluginManager] Read rom:/skyline/plugins/libarcropolis.nro
[PluginManager] Loading plugins...
[PluginManager] Loaded 'rom:/skyline/plugins/libarcropolis.nro'
[PluginManager] Running `main` for rom:/skyline/plugins/libarcropolis.nro
[HashesMgr]
Failed to read "rom:/skyline/hashes.txt" "(Result code: 514)"
[And64InlineHook] inline hook 0x7f4e2f6614->0x7f4abdc000 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x7f4e0e8998->0x7f4abdc024 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x7f4e0e94b8->0x7f4abdc048 successfully! 4 bytes overwritten
[
And64InlineHook] inline hook 0x7f4e0e90a8->0x7f4abdc06c successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x7f4e0e9138->0x7f4abdc090 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x7f4e549b70->0x344c1a08c8 successfully! 20 bytes overwritten
[And64InlineHook] inline hook 0x7f4e2f9550->0x344c1a1130 successfully! 20 bytes overwritten

[And64InlineHook] inline hook 0x7f4e347da0->0x344c1a0b00 successfully! 20 bytes overwritten
[And64InlineHook] inline hook 0x7f4e0e5520->0x344c1b35a0 successfully! 20 bytes overwritten
ARCropolis v2.0.0-beta3 - File replacement plugin is now installed
[PluginManager] Finished running `main` for 'rom:/skyline/plugins/libarcropolis.nro' (0x0)
[handleNnFsMountRom] Prevented game from double mounting as 'rom'
[TcpLogger] Logger initialized.

[ARC::Config] Configuration file successfully created

[ARCropolis updater] Failed to connect to update server 178.62.31.147

[ARCropolis updater] Os { code: 111, kind: Other, message: "unknown error" }



R:\Downloads>`

**Comment by AwesomeKirito** [comment]
I think you need a clean transfer, change yo umm mods to be compatible with arcropolis and try again

**Comment by GarnetSunset** [comment]
@AwesomeKirito do you have a way to run a trace on which mod is causing it?

**Comment by Raytwo** [comment]
There are no way to know precisely which mod is causing an issue except by looking at the context of what was being loaded close to the crash.
However judging by GarnetSunset's logs, this is indeed an issue with a mod you own (sorry for the very late reply btw), so you should remove a bunch of your mods until it stops crashing to isolate the problematic one.
